### ISSUE TITLE
Keep awake

### ISSUE THREAD

**Issue by krissen** [SlidePilot/SlidePilot-Remote#3]
### Feature description
Keep device awake.

### Problems this feature would solve
Currently, the screen will automatically turn off. This breaks the connection to the presenting device. It is more of a hassle to re-connect than simply to have been using the main device for going back and forward in the slides from the beginning.

### Additional context
To be honest, this is kind of a deal-breaker. The app is pretty much unusable without it. 

You could implement checks like "over 50% charged", or "charging", or even "connected to presenting device or not", and if one or some of the above fails, then auto-sleep is enabled.

**Comment by brabanod** [comment]
Thanks for mentioning this, you are right, this is very important. This improvement will be in the next release 1.1, which is going public tomorrow or day after tomorrow.
